### ISSUE TITLE
Jpg file with certain characters shows as 404

### ISSUE THREAD

**Issue by barepixels** [proximasan/sdxl_artist_styles_studies#1]
@proximasan On Windows, jpg files with special characters in the filename (e.g. é or à) shows up as 404 even though they exist in "grids" folder

For Example last name starts with "A"

Wäinö Aaltonen
Marina Abramović
Azzedine Alaïa
Sergio Aragonés
Andréi Arinouchkine
Eugène Atget
Marie Thérèse Auffray

![Artist Styles Studies](https://github.com/proximasan/sdxl_artist_styles_studies/assets/92839033/9e0e54a9-4b3b-42ad-a271-71f70beeaf97)

Tested with (windows) Chrome, Edge, Firefox, and Opera

**Comment by proximasan** [comment]
thanks for letting me know about this! should be solved now ✨

**Comment by barepixels** [comment]
how and where do I do the git pull?  Do I add that command somewhere?

**Comment by proximasan** [comment]
you open the folder you have of this repo in your terminal. like `cd <path-to-this-folder>` and then just `git pull`

**Comment by barepixels** [comment]
Thanks

**Comment by barepixels** [comment]
Hummm git pull said already up to date and didn't update.

But I manually downloaded and replaced "app.py" and it works now.  Thank you so much
